### PR TITLE
adding greater good badge for good labs branding

### PR DESCRIPTION
**Pull request by vsoch**
This will add the greater good badge as part of the Good Labs branding.

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by pdurbin** [comment]
@vsoch I don't mind if you merge this but I'm confused. I thought the idea was that the first step is to add the organization to https://good-labs.github.io/greater-good-affirmation/participate/ and **then** the organization gets a badge. (This also implies that the badge can be revoked.) Good Labs (or should it be SLOPI Communication?) doesn't appear under "project or community" there as of this writing:

Screen Shot 2019-05-08 at 5 22 15 PM

Or am I completely turned around on this? Instead of a centralized participants.csv list vetted by Good Labs, is the idea that anyone can add the badge to their repo? There's no enforcement? No ability to revoke a badge? I'm fine with the decentralized approach, the honor system if you will. People who want the Greater Good Affirmation button can self-select or opt in, if they want, in my view. But I'm not sure what you want. Maybe you want to add "Good Labs" or and/or "SLOPI Communication" to particpants.csv first? Please advise. 😄

**Comment by vsoch** [comment]
It’s sort of implied that “The Good Labs” that provides this pledge exists for the greater good, that’s our slogan is it not?

Regardless, this idea of not having a thing to sign - and just giving a definition and a badge, is interesting. It probably only hurts the effort to enforce a requirement of adding to the participants list, and then the entire affirmation is truly based on good faith. What do you think about that?

And I would +1 making available a SLOPI badge in addition.

**Comment by vsoch** [comment]
If you don’t mind merge, let’s do it! I’ll rework the affirmation repo to remove signing the file, and to show how to add the badge instead.

**Comment by vsoch** [comment]
Merging!

**Comment by vsoch** [comment]
see https://github.com/good-labs/greater-good-affirmation/pull/19

**Pull request merged**
